// <auto-generated />
using System;
using AnimalFostering.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimalFostering.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030174403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalFostering.API.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Breed = "Siamese",
                            CreatedAt = new DateTime(2025, 10, 30, 17, 44, 2, 455, DateTimeKind.Utc).AddTicks(2752),
                            Description = "Friendly and playful",
                            ImageUrl = "",
                            Name = "Whiskers",
                            Species = "Cat",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 30, 17, 44, 2, 455, DateTimeKind.Utc).AddTicks(2756)
                        },
                        new
                        {
                            Id = 2,
                            Age = 3,
                            Breed = "Golden Retriever",
                            CreatedAt = new DateTime(2025, 10, 30, 17, 44, 2, 455, DateTimeKind.Utc).AddTicks(4624),
                            Description = "Loyal and energetic",
                            ImageUrl = "",
                            Name = "Buddy",
                            Species = "Dog",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 30, 17, 44, 2, 455, DateTimeKind.Utc).AddTicks(4624)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
